# Generated by Django 3.1.5 on 2021-01-11 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('attachment', models.ImageField(null=True, upload_to='uploads/attachments/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(null=True, upload_to='uploads/thumbnails/%Y/%m/%d/')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('tripcode', models.CharField(max_length=40, null=True)),
                ('post_number', models.IntegerField()),
                ('from_ip', models.GenericIPAddressField()),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('subject', models.CharField(max_length=100)),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL)),
                ('on_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='boards.board')),
                ('replies_to', models.ManyToManyField(related_name='_topic_replies_to_+', to='boards.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('attachment', models.ImageField(null=True, upload_to='uploads/attachments/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(null=True, upload_to='uploads/thumbnails/%Y/%m/%d/')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('tripcode', models.CharField(max_length=40, null=True)),
                ('post_number', models.IntegerField()),
                ('from_ip', models.GenericIPAddressField()),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('on_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.board')),
                ('on_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.topic')),
                ('replies_to', models.ManyToManyField(related_name='_reply_replies_to_+', to='boards.Reply')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
