# Generated by Django 3.1.5 on 2021-01-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_bannedip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='replies_to',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='replies_to',
        ),
    ]
