# Generated by Django 3.1.5 on 2021-01-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20210112_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='banned_for',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='banned_for',
            field=models.BooleanField(default=False),
        ),
    ]
